### ISSUE TITLE
plugin won't load

### ISSUE THREAD

**Issue by anak-nolep** [tr7zw/YAPFA#253]
**Expected behavior**
Load plugin oh_The_Dungeons_You'll_Go properly like in papermc
![2020-10-13_19 55 57](https://user-images.githubusercontent.com/49714008/95864134-31af7980-0d8f-11eb-860f-03ebc18ad736.png)
on tuinity
![2020-10-13_20 35 18](https://user-images.githubusercontent.com/49714008/95867783-bb614600-0d93-11eb-903a-69b0bf70d3a6.png)

**Observed behavior**
Plugin won't load it on yatopia

**Steps to reproduce (if known)**
Download Oh The Dungeon You Go on spigot page
drag plugin to server plugin (just like normal plugin installation)

**Installed plugins**
![2020-10-13_19 48 37](https://user-images.githubusercontent.com/49714008/95864226-4986fd80-0d8f-11eb-837e-fdd3a78edc51.png)

**Version**
in screenshot

**Timings**
papermc
https://timings.aikar.co/?id=d6f1f21fdc884fd88dcd135c21ea2657
tuinity
https://timings.aikar.co/?id=38b4bf6a48fe49db998bcdbd480af244
yatopia
https://timings.aikar.co/?id=450028ed00d645d686c31f8cd1ec9823#timings

**Additional context**
all of my plugin are using default config
ignore nether view plugin its papermc fault i think

**Comment by MrIvanPlays** [comment]
```
[16:47:28 ERROR]: Error occurred while enabling Oh_the_dungeons_youll_go v8.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[])" because "is" is null
        at forge_sandbox.com.someguyssoftware.dungeons2.spawner.SpawnSheetLoader.exposeSpawnSheet(SpawnSheetLoader.java:200) ~[?:?]
        at otd.Main.onEnable(Main.java:123) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Yatopia-"9aa3822"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Yatopia-"9aa3822"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Yatopia-"9aa3822"]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Yatopia-"9aa3822"]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Yatopia-"9aa3822"]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:225) ~[patched_1.16.3.jar:git-Yatopia-"9aa3822"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:943) ~[patched_1.16.3.jar:git-Yatopia-"9aa3822"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.3.jar:git-Yatopia-"9aa3822"]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

The plugin fails to extract a file or to get a resource inside the jar. Saw code, JavaPlugin#getResource has not been modified by us. 

Not sure if that's newer javas' fuckery or everyone hates us. This is a plugin issue
