### ISSUE TITLE
Hide Join Quit Kick Messages enabled on Chatcontrol cause plugin kick errors

### ISSUE THREAD

**Issue by andris155** [tr7zw/YAPFA#299]
**Expected behavior**
 
Hide Join Quit Kick Messages enabled on Chatcontrol no cause plugin kick errors.
Paper server file does not have this error.

**Observed behavior**

Hide Join Quit Kick Messages enabled on Chatcontrol cause plugin kick errors.

**Steps to reproduce (if known)**

1. Install the Authme and the Chatcontrol plugins to Yatopia server.
2. Enable the Hide_Join_Quit_Kick_Messages option on the messages.yml
3. Login and wait the login timeout.
4. See kick error.

```
[22:29:25] [Server thread/WARN]: [AuthMe] Task #488 for AuthMe v5.6.0-SNAPSHOT-b2432 generated an exception
java.lang.NullPointerException: null
	at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:323) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:467) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at fr.xephi.authme.task.TimeoutTask.run(TimeoutTask.java:31) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1372) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:397) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1282) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1013) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[22:29:25] [Server thread/INFO]: andris155 lost connection: Login timeout exceeded, you have been kicked from the server, please try again!
```

**Installed plugins**

ChatControl Pro, AuthMe

**Version**

This server is running Yatopia version git-Yatopia-"23b9e93" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Timings**

**Additional context**

**Comment by toinouH** [comment]
Are you able to reproduce on Tuinity or Paper ?

**Comment by andris155** [comment]
Paper server file does not have this error.

**Comment by andris155** [comment]
I tested it and there is no such error with the Tuinity server file either.

**Comment by andris155** [comment]
Thanks
