### ISSUE TITLE
Failed to handle packet for /IP address sometimes

### ISSUE THREAD

**Issue by andris155** [tr7zw/YAPFA#300]
**Expected behavior**
 
No this error.

**Observed behavior**

Failed to handle packet for /IP address sometimes.

```
[22:01:03] [User Authenticator #262/INFO]: UUID of player OliverHahn01 is 75f0c875-2b34-3e2e-bdec-10fb93c9a788
[22:01:03] [Server thread/INFO]: OliverHahn01[/IP address:50546] logged in with entity id 7847 at ([world]1742.5869833784445, 47.0, -893.5038621690435)
[22:01:48] [Craft Scheduler Thread - 397 - AuthMe/INFO]: [AuthMe] OliverHahn01 logged in IP address
[22:01:48] [Server thread/WARN]: OliverHahn01 was kicked due to keepalive timeout!
[22:01:48] [Server thread/WARN]: Failed to handle packet for /IP address:50546
java.lang.NullPointerException: null
	at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:323) ~[patched_1.16.4.jar:git-Yatopia-"a47bfa7"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:293) ~[patched_1.16.4.jar:git-Yatopia-"a47bfa7"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:238) ~[patched_1.16.4.jar:git-Yatopia-"a47bfa7"]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:543) ~[patched_1.16.4.jar:git-Yatopia-"a47bfa7"]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:150) ~[patched_1.16.4.jar:git-Yatopia-"a47bfa7"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1460) ~[patched_1.16.4.jar:git-Yatopia-"a47bfa7"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:397) ~[patched_1.16.4.jar:git-Yatopia-"a47bfa7"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1282) ~[patched_1.16.4.jar:git-Yatopia-"a47bfa7"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1013) ~[patched_1.16.4.jar:git-Yatopia-"a47bfa7"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Yatopia-"a47bfa7"]
	at java.lang.Thread.run(Unknown Source) [?:?]
[22:01:48] [Server thread/INFO]: OliverHahn01 lost connection: Timed out
```

**Steps to reproduce (if known)**

**Installed plugins**

Plugins (28): AuthMe, BetterGUI, ChatControl, Citizens, ConditionalCommands, CoreProtect, EasySetSpawn*, FastLogin, HolographicDisplays, HolographicExtension, ImageMaps, ItemJoin, LPC, LuckPerms, NoCheatPlus, PlaceholderAPI, PlayerVedelem, PlugMan, ProtocolLib, SkinsRestorer, StaffChat, SuperTrailsPro*, TAB, Vault, WDLCompanion*, WorldBorder, WorldEdit, WorldGuard

**Version**

This server is running Yatopia version git-Yatopia-"a47bfa7" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Timings**

**Additional context**

**Comment by MrIvanPlays** [comment]
Caused by the same thing reported in #299
