### ISSUE TITLE
Incompatibility with plugin Magic

### ISSUE THREAD

**Issue by mibby** [tr7zw/YAPFA#313]
**Expected behavior**
No errors in start-up log.

**Observed behavior**
```
[05:40:17] [Server thread/INFO]: [Magic] Enabling Magic v8.2-SNAPSHOT-aa1db08
[05:40:17] [Server thread/WARN]: [Magic] [33m An error occurred, setting arrow lifespan will not work[0m
java.lang.NoSuchFieldException: ar
	at java.lang.Class.getDeclaredField(Class.java:2489) ~[?:?]
	at com.elmakers.mine.bukkit.utility.NMSUtils.initialize(NMSUtils.java:1513) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicPlugin.onEnable(MagicPlugin.java:171) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Yatopia-"098c015"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Yatopia-"098c015"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Yatopia-"098c015"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Yatopia-"098c015"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Yatopia-"098c015"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.4.jar:git-Yatopia-"098c015"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:259) ~[patched_1.16.4.jar:git-Yatopia-"098c015"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:941) ~[patched_1.16.4.jar:git-Yatopia-"098c015"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:180) ~[patched_1.16.4.jar:git-Yatopia-"098c015"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[05:40:17] [Server thread/INFO]: [Magic] Using backwards-compatibility layer. It is highly recommended that you update to the latest Spigot version and/or the latest Magic version.
[05:40:17] [Server thread/INFO]: [Magic] EffectLib initialized
[05:40:17] [Server thread/INFO]: [Magic] Magic player data saving is disabled
[05:40:17] [Server thread/INFO]: [Magic] Skin-based spell icons disabled
[05:40:17] [Server thread/INFO]: [Magic] SkillAPI integration disabled
[05:40:17] [Server thread/INFO]: [Magic] Vault found, 'currency' cost types available
[05:40:17] [Server thread/INFO]: [Magic] LibsDisguises found, mob disguises and disguise_restricted features enabled
[05:40:17] [Server thread/INFO]: [Magic] Integrated with MobArena, use "magic:<itemkey>" in arena configs for Magic items, magic mobs can be used in monster configurations
[05:40:17] [Server thread/INFO]: [Magic] LogBlock integration disabled
[05:40:17] [Server thread/INFO]: [Magic] Integrating with Essentials for vanish detection
[05:40:17] [Server thread/INFO]: [Magic] Integrating with Essentials for Recall warps
[05:40:17] [Server thread/INFO]: [Magic] Factions integration disabled
[05:40:17] [Server thread/INFO]: [Magic] WorldGuard found, will respect build permissions for construction spells
[05:40:17] [Server thread/INFO]: [Magic] Multiverse-Core found, will respect PVP settings
[05:40:17] [Server thread/INFO]: [Magic] PreciousStones manager disabled, field protection and pvp checks will not be used.
[05:40:17] [Server thread/INFO]: [Magic] Towny manager disabled, region protection and pvp checks will not be used.
[05:40:17] [Server thread/INFO]: [Magic] Lockette/LockettePro integration disabled
[05:40:17] [Server thread/INFO]: [Magic] GriefPrevention manager disabled, claim protection will not be used.
[05:40:17] [Server thread/INFO]: [Magic] NoCheatPlus found, adding exemption handlers.
[05:40:17] [Server thread/INFO]: [Magic] dynmap found, integrating.
[05:40:17] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: magic
[05:40:17] [Server thread/INFO]: [Magic] PlaceholderAPI integration enabled. Available placeholders:
[05:40:17] [Server thread/INFO]: [Magic] magic_path, magic_class, magic_wand, magic_spell, magic_mana, magic_mana_max, magic_sp, magic_spell_count
[05:40:17] [Server thread/INFO]: [Magic] LightAPI integration disabled.
[05:40:17] [Server thread/INFO]: [Magic] Skript integration disabled.
[05:40:17] [Server thread/INFO]: [Magic] Citadel integration disabled.
[05:40:17] [Server thread/INFO]: [Magic] Activated BStats
[05:40:17] [Server thread/INFO]: [Magic] Registered currencies: item,mana,xp,health,currency,sp,levels,hunger
[05:40:17] [Server thread/INFO]: [Magic] Loaded 0 attributes
[05:40:17] [Server thread/INFO]: [Magic] Registered attributes: [health_max, bowpull, damage, damage_dealt, level, location_x, health, location_y, bowpower, moon, mana, location_z, xp, mana_max, time]
[05:40:17] [Server thread/INFO]: [Magic] Loaded 2 effect lists
[05:40:17] [Server thread/INFO]: [Magic] Loaded 7 items
[05:40:17] [Server thread/INFO]: [Magic] Loaded 473 wands
[05:40:17] [Server thread/INFO]: [Magic] Loaded 4 spells
[05:40:17] [Server thread/INFO]: [Magic] Loaded 0 classes
[05:40:17] [Server thread/INFO]: [Magic] Loaded 0 classes
[05:40:17] [Server thread/INFO]: [Magic] Loaded 0 progression paths
[05:40:17] [Server thread/INFO]: [Magic] Loaded 0 mob templates
[05:40:17] [Server thread/INFO]: [Magic] Loaded 2 automata templates
[05:40:17] [Server thread/INFO]: [Magic] Loaded 0 crafting recipes
[05:40:17] [Server thread/INFO]: [Magic] Loaded 0 customized worlds
[05:40:17] [Server thread/INFO]: [Magic] Finished reloading configuration
```

**Steps to reproduce (if known)**
* Swapped from Paper to Yatopia for testing.
* Noticed new error.

**Installed plugins**
Magic dev 3424
https://jenkins.elmakers.com/view/all/job/MagicPlugin/

**Version**
Yatopia version git-Yatopia-"098c015" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
(Yatopia leaflight/ver/1.16.4 dev 6)

**Additional context**
This error did not occur with Paper dev 320 (Spigot 1.16.4). 

Could an arrow based patch be rewriting the declared field to an older version or breaking the version check? Magic seems to fall back to v1.8.3's ``class_EntityArrow_lifeField = class_EntityArrow.getDeclaredField("ar");`` instead of the first try for 1.13's ``class_EntityArrow_lifeField = class_EntityArrow.getDeclaredField("despawnCounter");``.

https://github.com/elBukkit/MagicPlugin/blob/692ebe10cb1cc2b2d70adfa9c1e500352859ce4f/CompatibilityLib/src/main/java/com/elmakers/mine/bukkit/utility/NMSUtils.java#L1498-L1524

**Comment by MrIvanPlays** [comment]
the plugin doesn't work on purpur too because billy changed it so that this field is now in IProjectile to make it for all projectiles instead of in EntityArrow.
it is a plugin issue, and the plugin should adapt. we're not gonna revert that change.
