### ISSUE TITLE
Error whilst processing packet net.minecraft.server.v1_16_R3.PacketPlayInUseItem

### ISSUE THREAD

**Issue by andris155** [tr7zw/YAPFA#316]
**Expected behavior**
 
No error on packet processing.

**Observed behavior**

Sometime error when packet processing. 
```
[21:58:39] [Server thread/ERROR]: Error whilst processing packet net.minecraft.server.v1_16_R3.PacketPlayInUseItem@1576e0f0 for maryhonaly[/IP address:38248]
java.lang.NullPointerException: null
	at net.minecraft.server.v1_16_R3.EntityPlayer.openSign(EntityPlayer.java:1244) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.ItemStack.placeItem(ItemStack.java:351) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:563) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1555) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:151) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:114) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1202) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1195) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:97) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1335) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1010) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:180) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at java.lang.Thread.run(Unknown Source) [?:?]
[21:58:39] [Server thread/INFO]: maryhonaly lost connection: Packet processing error
```

**Steps to reproduce (if known)**

**Installed plugins**

`Plugins (112): AdminVedelem, antiRedstoneClock, ArmorStandEditor, BetterGUI, Bridge, BungeeHelpop, BuntetesLogolo, ChatControl, CheckpointAddon, ChestShop, ChestSort, ChristmasCalendar*, Citizens, CombatLogX, CommandHook, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, CS-CoreLib, Duels, DyedBackpacks, EcoPower, EnderContainers, EntityDetection, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, EventekGUI, EventRendszer, ExtraGear, ExtraTools, FastAsyncWorldEdit (WorldEdit), FluffyMachines, GPAccruals*, GriefPrevention, GriefPreventionFlags, HeadDatabase, HideAndSeek, HolographicDisplays, HonapStaffja, HotbarPets, HungerGames, Jatekido, Kemkedes, Kezdes, LibsDisguises, LiteXpansion, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobArena, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NoCheatPlus, NoSpawnerChange, OpenInv, Paintball, PickupSpawners, PlaceholderAPI, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, PomaBot, PomaDrops, PomaExpansion, PotionArmors, PremiumAds*, ProtocolLib, RabbitsVSPenguins, RedstoneClockDetector, RemoveUnbreaking, RestrictedCreative, Shopkeepers, SkinsRestorer, sleep-most, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimefunPomaFix, SpleefPlusPlus, StaffChat, StaffTime, SzulinapiKalapok, TAB, TimeIsMoney*, TokenManager, TokenShopEditor, TokenStaff*, TreasureChest, Vault, Votifier, VotingPlugin, WDLCompanion*, WDLCompanionGriefPreventionSupport*, Wild, WorldBorder, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags`

**Version**

his server is running Yatopia version git-Yatopia-"04855bf" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Timings**

**Additional context**

**Comment by andris155** [comment]
This error may have been caused by this sign.
![130936969_1103747300055888_4581789899344304665_n](https://user-images.githubusercontent.com/8324198/102018902-82802600-3d70-11eb-8b0e-24f128af6db6.png)

**Comment by MrIvanPlays** [comment]
please try reproducing using latest build.
