### ISSUE TITLE
ProtocolSupport is not loading with latest version of yatopia

### ISSUE THREAD

**Issue by REALMWTH** [tr7zw/YAPFA#354]
**Expected behavior**
Plugin loads without any issues.

**Observed behavior**
Plugin's load is failed, throwing an error in log.

**Steps to reproduce (if known)**
Download latest dev build of ProtocolSupport plugin and try to load it with latest version of Yatopia 1.16.5
link: https://build.true-games.org/job/ProtocolSupport/

**Installed plugins**
ProtocolSupport

**Version**
This server is running Yatopia version git-Yatopia-8 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Timings**

**Additional context**
Some info from log file:

```
[13:11:53] [Server thread/INFO]: [ProtocolSupport] Loading ProtocolSupport v1.16.5-1-dev
[13:11:53] [Server thread/INFO]: [ProtocolSupport] Detected Spigot server implementation type
[13:11:53] [Server thread/INFO]: [ProtocolSupport] Status threads max count: 2, keep alive time: 60
[13:11:53] [Server thread/INFO]: [ProtocolSupport] Login threads keep alive time: 60
[13:11:53] [Server thread/ERROR]: [ProtocolSupport] Error when loading, shutting down
java.lang.NoSuchFieldError: b
	at protocolsupport.zplatform.impl.spigot.SpigotMiscUtils.getServerIOEventLoopGroup(SpigotMiscUtils.java:298) ~[?:?]
	at protocolsupport.protocol.packet.PacketData.<clinit>(PacketData.java:19) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:315) ~[?:?]
	at protocolsupport.ProtocolSupport.lambda$onLoad$0(ProtocolSupport.java:73) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:71) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Yatopia-8]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.16.5.jar:git-Yatopia-8]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:943) ~[patched_1.16.5.jar:git-Yatopia-8]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Yatopia-8]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by toinouH** [comment]
@REALMWTH could you try this pr ? https://github.com/YatopiaMC/Yatopia/pull/355

**Comment by REALMWTH** [comment]
@toinouH sure, will try it now

**Comment by REALMWTH** [comment]
Update: just checked the build of pr, plugin loads now without any issues. Thanks a lot! ;)

**Comment by ishland** [comment]
Don't close this yet because that pr didnt get merged
