### ISSUE TITLE
Yatopia breaking plugin compatibility.

### ISSUE THREAD

**Issue by mibby** [tr7zw/YAPFA#376]
**Expected behavior**
Plugins to initialize fine as it does on Paper & Tuinity.

**Observed behavior**
Various plugins breaking during start-up initialization.

**Steps to reproduce (if known)**
Use Yatopia.

**Installed plugins**
See log.

**Version**
Yatopia dev/threaded-worldgen (action build 1316) (https://github.com/YatopiaMC/Yatopia/commit/099091149df02eb68bfb49e6ba456fb476b2d68b).

The errors to look out for;

* PlotSquared - SQLException: No suitable driver found for
* LibsDisguises - NoClassDefFoundError: org/bukkit/configuration/InvalidConfigurationException
* TitleManager - RuntimeException: java.lang.ClassNotFoundException: org.bukkit.Bukkit

-snip-

Using the exact same setup environment but with Tuinity dev/playerchunkloading (action build 451) (https://github.com/Spottedleaf/Tuinity/commit/28303240ee2151a6e3827395850521d523e60ad6), there are 0 plugin compatibility or start-up errors.

-snip-

I like testing development branches to get ahead of any issues and figured I'd forward upstream the breaking changes.

**Comment by ishland** [comment]
Can you try reproduce using `cache/1.16.5/Minecraft/1.16.5-patched.jar` as server jar?

**Comment by mibby** [comment]
The patched jar located in ``cache/1.16.5/Minecraft/1.16.5-patched.jar`` does seem to start up fine without any plugins erroring (ignoring the Yatopia warnings). So I assume this is a patcher issue then with it not loading the correct jar once created?

**Comment by ishland** [comment]
- 7a85548a46e841ec5db3481154e9f11afa2e1dd2
- 8e98f4bad9c0b3061ee9aea67932f47f00584054

**Comment by mibby** [comment]
Thanks for the quick turnaround!

**Comment by mibby** [comment]
@ishland This is still broken as of git-Yatopia-dev/threaded-worldgen-"6e8c4fa" (actions build 1319) for the plugin LibsDisguises.

```
[01:45:26] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.21-SNAPSHOT
[01:45:26] [Server thread/INFO]: [LibsDisguises] File Name: LibsDisguises.jar
[01:45:26] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_16_R3
[01:45:26] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #856
[01:45:26] [Server thread/INFO]: [LibsDisguises] Build Date: 30/01/2021 07:23
[01:45:26] [Server thread/ERROR]: Error occurred while enabling LibsDisguises v10.0.21-SNAPSHOT (Is it up to date?)
[01:45:26] [Server thread/ERROR]: Suspected Plugins: 
[01:45:26] [Server thread/ERROR]: 	LibsDisguises{enabled,ver=10.0.21-SNAPSHOT,path=plugins\LibsDisguises.jar}
[01:45:26] [Server thread/ERROR]: Exception details below: 
java.lang.NoClassDefFoundError: org/bukkit/configuration/InvalidConfigurationException
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_51]
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048) ~[?:1.8.0_51]
	at java.lang.Class.getMethod0(Class.java:3018) ~[?:1.8.0_51]
	at java.lang.Class.getMethod(Class.java:1784) ~[?:1.8.0_51]
	at me.libraryaddict.disguise.utilities.LibsPremium.getInformation(LibsPremium.java:118) ~[?:?]
	at me.libraryaddict.disguise.utilities.LibsPremium.doSecondaryCheck(LibsPremium.java:188) ~[?:?]
	at me.libraryaddict.disguise.utilities.LibsPremium.check(LibsPremium.java:315) ~[?:?]
	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:139) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[1.16.5-patched.jar:git-Yatopia-dev/threaded-worldgen-"6e8c4fa"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[1.16.5-patched.jar:git-Yatopia-dev/threaded-worldgen-"6e8c4fa"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[1.16.5-patched.jar:git-Yatopia-dev/threaded-worldgen-"6e8c4fa"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[1.16.5-patched.jar:git-Yatopia-dev/threaded-worldgen-"6e8c4fa"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[1.16.5-patched.jar:git-Yatopia-dev/threaded-worldgen-"6e8c4fa"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:466) ~[1.16.5-patched.jar:git-Yatopia-dev/threaded-worldgen-"6e8c4fa"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:254) ~[1.16.5-patched.jar:git-Yatopia-dev/threaded-worldgen-"6e8c4fa"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:947) ~[1.16.5-patched.jar:git-Yatopia-dev/threaded-worldgen-"6e8c4fa"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[1.16.5-patched.jar:git-Yatopia-dev/threaded-worldgen-"6e8c4fa"]
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3057/1306957628.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: org.bukkit.configuration.InvalidConfigurationException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	... 20 more
[01:45:26] [Server thread/INFO]: [LibsDisguises] Disabling LibsDisguises v10.0.21-SNAPSHOT
```

For reference, LibsDisguises premium features require the premium jar from Spigot be placed in the LibsDisguises folder. Then you can use dev builds in the root plugin folder just fine and have premium features unlocked. I assume the issue has something to do with it checking another jar on initialize?

Using the jar found in ``cache/1.16.5/Minecraft/1.16.5-patched.jar``, no error. So the loader / patcher jar is still not useable.

**Comment by ishland** [comment]
b8d5b1c85bbb9fe6d3a7329581540902b2d59d1d
525de707e7bc4a9ce7f32e5866b370aae3ad9122
