### ISSUE TITLE
"hash do not match" after updating

### ISSUE THREAD

**Issue by xenorio** [tr7zw/YAPFA#439]
**Expected behavior**
Server starting normally

**Observed behavior**
Server is immediately crashing with errors

**Steps to reproduce (if known)**
1 - Update Yatopia from 1.16.4 to latest 1.16.5 build
2 - Start Yatopia
3 - Profit

**Installed plugins**
None

**Version**
1.16.5 Build 41

**Additional context**
```
Applying patches...
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: Hash do not match
        at org.yatopiamc.yatoclip.YatoclipPatcher.patchJar(YatoclipPatcher.java:151)
        at org.yatopiamc.yatoclip.ServerSetup.applyMappingsAndPatches(ServerSetup.java:92)
        at org.yatopiamc.yatoclip.ServerSetup.setup(ServerSetup.java:50)
        at org.yatopiamc.yatoclip.Yatoclip.main(Yatoclip.java:18)
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: Hash do not match
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.yatopiamc.yatoclip.YatoclipPatcher$1.lambda$newThread$0(YatoclipPatcher.java:99)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: Hash do not match
        at org.yatopiamc.yatoclip.YatoclipPatcher.lambda$null$2(YatoclipPatcher.java:118)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        ... 4 more
Caused by: java.io.FileNotFoundException: Hash do not match
        at org.yatopiamc.yatoclip.YatoclipPatcher.getPatchedBytes(YatoclipPatcher.java:170)
        at org.yatopiamc.yatoclip.YatoclipPatcher.lambda$null$2(YatoclipPatcher.java:116)
        ... 5 more
```

**Comment by xenorio** [comment]
Verified same behavior with fresh install on a different machine, with more output: https://pastebin.com/G1CbP22k

**Comment by Justsnoopy30** [comment]
Same here.

**Comment by tommasobenatti** [comment]
it gives this problem not only when upgrading from 1.16.4 to 1.16.5 but when yatopia needs to create the cache folder

**Comment by axisiscool** [comment]
Same here... happened when creating a brand new server (after cache folder create) with the build 33 jar

**Comment by Modd3d** [comment]
+1

**Comment by Modd3d** [comment]
use latest build

**Comment by toinouH** [comment]
I think we can close this now. Waiting an approval to do it.
