### ISSUE TITLE
Can't apply patches

### ISSUE THREAD

**Issue by magikzoro** [tr7zw/YAPFA#445]
Applying patches...
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: Hash do not match
        at org.yatopiamc.yatoclip.YatoclipPatcher.patchJar(YatoclipPatcher.java:151)
        at org.yatopiamc.yatoclip.ServerSetup.applyMappingsAndPatches(ServerSetup.java:92)
        at org.yatopiamc.yatoclip.ServerSetup.setup(ServerSetup.java:50)
        at org.yatopiamc.yatoclip.Yatoclip.main(Yatoclip.java:18)
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: Hash do not match
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.yatopiamc.yatoclip.YatoclipPatcher$1.lambda$newThread$0(YatoclipPatcher.java:99)
        at org.yatopiamc.yatoclip.YatoclipPatcher$1$$Lambda$10/972404515.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: Hash do not match
        at org.yatopiamc.yatoclip.YatoclipPatcher.lambda$null$2(YatoclipPatcher.java:118)
        at org.yatopiamc.yatoclip.YatoclipPatcher$$Lambda$9/438660480.get(Unknown Source)
        ... 6 more
Caused by: java.io.FileNotFoundException: Hash do not match
        at org.yatopiamc.yatoclip.YatoclipPatcher.getPatchedBytes(YatoclipPatcher.java:170)
        at org.yatopiamc.yatoclip.YatoclipPatcher.lambda$null$2(YatoclipPatcher.java:116)
        ... 7 more

**Comment by Titaniumtown** [comment]
Update to the latest build
