### ISSUE TITLE
failed to access class net.minecraft.server.v1_16_R3.BlockProperties

### ISSUE THREAD

**Issue by Baterka** [tr7zw/YAPFA#457]
**Expected behavior**
No error, should start normally.

**Observed behavior**
Plugin SuperiorSkyblock2 reporting error:
```
[org.bukkit.craftbukkit.v1_16_R3.CraftServer] failed to access class net.minecraft.server.v1_16_R3.BlockProperties from class com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_16_R3 (net.minecraft.server.v1_16_R3.BlockProperties is in unnamed module of loader 'app'; com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_16_R3 is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @26bfa07a) initializing SuperiorSkyblock2 v1.6.0 (Is it up to date?)
java.lang.IllegalAccessError: failed to access class net.minecraft.server.v1_16_R3.BlockProperties from class com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_16_R3 (net.minecraft.server.v1_16_R3.BlockProperties is in unnamed module of loader 'app'; com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_16_R3 is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @26bfa07a)
    at com.bgsoftware.superiorskyblock.nms.NMSBlocks_v1_16_R3.<clinit>(NMSBlocks_v1_16_R3.java:142) ~[?:?]
    at java.lang.Class.forName0(Native Method) ~[?:?]
    at java.lang.Class.forName(Class.java:315) ~[?:?]
    at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.loadNMSAdapter(SuperiorSkyblockPlugin.java:283) ~[?:?]
    at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onLoad(SuperiorSkyblockPlugin.java:119) ~[?:?]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"9237750"]
    at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:273) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"9237750"]
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"9237750"]
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"9237750"]
    at java.lang.Thread.run(Thread.java:834) [?:?]
```
starting with build: https://github.com/YatopiaMC/Yatopia/actions/runs/720649246
(older builds are working fine, seems like naming convention problems)

**Steps to reproduce (if known)**
Use Yatopia https://github.com/YatopiaMC/Yatopia/actions/runs/720649246 or newer...
Use SuperiorSkyblock2 https://hub.bg-software.com/job/SuperiorSkyblock2/113/ or newer...

**Installed plugins**
None, just SSB2

**Version**
https://github.com/YatopiaMC/Yatopia/actions/runs/720649246

**Timings**
Not important

**Comment by Titaniumtown** [comment]
Was stated in the discord server that this was fixed by an update of SSB2
