### ISSUE TITLE
Problem with some plugins on new Yatopia versions

### ISSUE THREAD

**Issue by wiktor-jozwiak** [tr7zw/YAPFA#466]
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:102) ~[?:?]
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:321) ~[?:?]
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108) ~[?:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[?:?]
	at de.light.economy.storage.PlayerBankSQL.createTable(PlayerBankSQL.java:54) ~[?:?]
	at de.light.economy.organisation.Main.onEnable(Main.java:188) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-80]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-80]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-80]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-80]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-80]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:582) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-80]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:302) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-80]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1064) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-80]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-80]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:183) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-80]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:89) ~[?:?]
	... 16 more

**Comment by Titaniumtown** [comment]
This is a plugin issue. Ask the plugin dev to update.
