### ISSUE TITLE
/version shows an error

### ISSUE THREAD

**Issue by dapelikaan** [tr7zw/YAPFA#506]
**Expected behavior**
something like this
```
[12:30:02 INFO]: This server is running Tuinity version git-Tuinity-"f0e91a4" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 7 version(s) behind
Previous version: git-Paper-312 (MC: 1.16.4)
```

**Observed behavior**
```
[11:25:27 INFO]: Checking version, please wait...
[11:25:27 WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://ci.codemc.io/job/YatopiaMC/job/Yatopia/job/ver%2F1.16.5/lastStableBuild/buildNumber
[11:25:27 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
[11:25:27 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[11:25:27 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[11:25:27 WARN]:        at java.net.URL.openStream(URL.java:1068)
[11:25:27 WARN]:        at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
[11:25:27 WARN]:        at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456)
[11:25:27 WARN]:        at com.google.common.io.CharSource.openBufferedStream(CharSource.java:107)
[11:25:27 WARN]:        at org.yatopiamc.yatopia.server.YatopiaVersionFetcher.fetchDistanceFromJenkins(YatopiaVersionFetcher.java:76)
[11:25:27 WARN]:        at org.yatopiamc.yatopia.server.YatopiaVersionFetcher.getUpdateStatusMessage(YatopiaVersionFetcher.java:56)
[11:25:27 WARN]:        at org.yatopiamc.yatopia.server.YatopiaVersionFetcher.getVersionMessage(YatopiaVersionFetcher.java:47)
[11:25:27 WARN]:        at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:205)
[11:25:27 WARN]:        at org.bukkit.command.defaults.VersionCommand.access$000(VersionCommand.java:30)
[11:25:27 WARN]:        at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:189)
[11:25:27 WARN]:        at java.lang.Thread.run(Thread.java:748)
[11:25:27 INFO]: This server is running Yatopia version git-Yatopia-ver/1.16.5-118 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Previous version: git-Tuinity-"f88659c" (MC: 1.16.5)
Error obtaining version information
```

**Steps to reproduce (if known)**
type `/version`

**Installed plugins**
`AdvancedBan, AsyncWorldEdit, ClearLag, CoreProtect, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, GroupManager, HolographicDisplays, ID-Library, LibsDisguises, MOTD, PlugMan, ProtocolLib, Stress, TAB, Vault, WorldEdit, WorldGuard`

**Version**
`git-Yatopia-ver/1.16.5-118`

**Comment by pthoelken** [comment]
Seems to be fixed at  120

```
[18:39:28 INFO]: Checking version, please wait...
[18:39:28 INFO]: This server is running Yatopia version git-Yatopia-ver/1.16.5-120 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Previous version: git-Yatopia-ver/1.16.5-118 (MC: 1.16.5)
You are running the latest version
```

**Comment by dapelikaan** [comment]
Nope, still have the same problem in 120, i guess its just something with this server then

**Comment by Titaniumtown** [comment]
This happens when there is an issue connecting to the jenkins. This is caused by how your network is set up.

**Comment by dapelikaan** [comment]
Hmmm weird but thanks, its weird that Yatopia is the only one i have this issue with.

**Comment by Toffikk** [comment]
I have a similiar issue , but it doesnt show stacktrace and it says `Unknown version`

**Comment by Titaniumtown** [comment]
on 1.16.5? That shouldn't be related.
